### ISSUE TITLE
Is there way to extract coordinates

### ISSUE THREAD

**Issue by SuryaViswanath11** [karolzak/boxdetect#15]
Hi,

I am working with pdf files and I came across the box-detect library. Thanks for creating this amazing library. I am using the following PDF file
[Form_49A.PDF](https://github.com/karolzak/boxdetect/files/6222509/Form_49A.PDF)
I am trying to annotate over the pdf file, however, for achieving this I was looking at ways to extract these boxes and then annotate. Is there a way to extract the coordinates for the boxes present in the pdf-file?

**Comment by karolzak** [comment]
Hi @SuryaViswanath11 ,
Glad to hear you found BoxDetect useful.
To use BoxDetect functions you need to first convert your PDF to images which is a fairly simple task. You can use one of few available packages to do it, like [pdf2image](https://pypi.org/project/pdf2image/)

**Comment by teohsinyee** [comment]
> Hi @SuryaViswanath11 , Glad to hear you found BoxDetect useful. To use BoxDetect functions you need to first convert your PDF to images which is a fairly simple task. You can use one of few available packages to do it, like [pdf2image](https://pypi.org/project/pdf2image/)

Seems there is no direct answer to the question, Is there a way to extract the coordinates for the boxes present in the image file?

**Comment by karolzak** [comment]
Hi @teohsinyee 
Each function from BoxDetect takes an image as input and returns a collection of coordinates for detected boxes (based on config params).
Example:
```python
from boxdetect.pipelines import get_boxes

rects, grouping_rects, image, output_image = get_boxes(
    file_name, cfg=cfg, plot=False)

print(grouping_rects)

OUT:
# (x, y, w, h)
[(276, 276, 1221, 33),
 (324, 466, 430, 33),
 (384, 884, 442, 33),
 (985, 952, 410, 32),
 (779, 1052, 156, 33),
 (253, 1256, 445, 33)]
```

```python
import matplotlib.pyplot as plt

plt.figure(figsize=(20,20))
plt.imshow(output_image)
plt.show()
```
![image](https://user-images.githubusercontent.com/9843623/162154955-23732e30-2c1e-4002-a6a3-98afad0b1732.png)

Another:
```python
from boxdetect.pipelines import get_checkboxes

checkboxes = get_checkboxes(
    file_path, cfg=cfg, px_threshold=0.1, plot=False, verbose=True)

print("Output object type: ", type(checkboxes))
for checkbox in checkboxes:
    print("Checkbox bounding rectangle (x,y,width,height): ", checkbox[0])
    print("Result of `contains_pixels` for the checkbox: ", checkbox[1])
    print("Display the cropout of checkbox:")
    plt.figure(figsize=(1,1))
    plt.imshow(checkbox[2])
    plt.show()
```
![image](https://user-images.githubusercontent.com/9843623/162154503-49b2c20e-28bf-46f5-9112-8fe515609bbb.png)
