### ISSUE TITLE
challenging case on checkbox crossing outside box

### ISSUE THREAD

**Issue by robbiedood** [karolzak/boxdetect#17]
Dear Boxdetect friends and the author Karolzak,

My image is as shown attached, checked X crossing a little bit outside the box. So far we can not detect any checkbox, tried different configs. Hope to hear your expertise on the challenging case.
![boxdetect_failcase](https://user-images.githubusercontent.com/36803293/125356332-ec6aa900-e31a-11eb-8fb4-33aecff89ccb.png)
 
Best,
--Luke

**Comment by karolzak** [comment]
Hey @lukelu0520 
Just by looking at the example you shared, seems like BoxDetect should handle that with a correct config.
Is that image you share an actual document you're using as an input for BoxDetect or are you using a bigger image/doc? Can you share an example of a full size doc that you're using?

**Comment by lukelu520** [comment]
Hi @karolzak , I am grateful to get your response. Yes, the image is what we are using as an input for BoxDetect. 

The latest update: after reading your source code (very neat coding & comprehensive comments!), we figured out that setting morph_kernels_type = 'rectangles' could solve the problem.  'rectangles' type takes longer processing but it works !

Thanks for creating BoxDetect !
--Luke

**Comment by lukelu0520** [comment]
Update: We are investing more cases and found that below one is even more challenging. Using rectangles still misses many checked boxes (see attached images). 

The image we are using as an input of BoxDetect:
![Seller_Disclosure_cropped](https://user-images.githubusercontent.com/36803293/125526456-9a09b034-89d4-4d57-9cdf-1d3c8e9f07da.png)


The output from BoxDetect:
![Figure_1](https://user-images.githubusercontent.com/36803293/125526599-7ae1bf8f-cdbb-4c7e-8d7e-fc2ca332de64.png)


Hope to hear your expertise on the challenging case.

Best,
--Luke
