### ISSUE TITLE
checkbox detect fails with sloppy crosses

### ISSUE THREAD

**Issue by FUF1** [karolzak/boxdetect#19]
Hi, amazing module! Very useful. I use it to detect student answers in a research project.

Some of the students make the crosses over the border of the checkbox. Most of the time those square checkboxes seem to be not detected, many others get detected reliably. I tried many different values in the config. Any suggestions on how to proceed a bit smarter than just guessing values?
I attached some images of undetected and detected ones (the blue marks are made by the program to do a manual check. If a checkbox is detected as "checked" the blue square is filled out).

```
cfg.width_range = (25,42)
cfg.height_range = (25,42)
cfg.scaling_factors = [0.5]
cfg.wh_ratio_range = (0.3, 1.6)
cfg.dilation_iterations = 0
```
![image](https://user-images.githubusercontent.com/69962736/147509384-770dff16-d921-4cd9-8bf2-06f605b85128.png)
![image](https://user-images.githubusercontent.com/69962736/147509403-91e31afd-21be-49f4-8b9d-1575c3c88ad1.png)
![image](https://user-images.githubusercontent.com/69962736/147509417-2c10d8b4-9486-46d9-b3cf-506992d3c3b4.png)

**Comment by karolzak** [comment]
Hi @FUF1,
Glad you found my package useful :)
BoxDetect should be perfect for your type of input. Try the following:
```python
# 2nd step would be to try making sure this width and height ranges are correct for your size of boxes
# it's best to open something like paint or so and just manually validate that your boxes are in fact within this pixel range
cfg.width_range = (25,42)
cfg.height_range = (25,42)
# 1st step would be to change scaling_factors to something like [0.8] or [0.7]
cfg.scaling_factors = [0.75]
# you know you're looking just for squares so you can limit wh_ratio_range to something like: (0.8, 1.2)
cfg.wh_ratio_range = (0.8, 1.2)
cfg.dilation_iterations = 0
```

Do let me know how it went! Good luck!

**Comment by FUF1** [comment]
> Hi @FUF1, Glad you found my package useful :) BoxDetect should be perfect for your type of input. Try the following:
> 
> ```python
> # 2nd step would be to try making sure this width and height ranges are correct for your size of boxes
> # it's best to open something like paint or so and just manually validate that your boxes are in fact within this pixel range
> cfg.width_range = (25,42)
> cfg.height_range = (25,42)
> # 1st step would be to change scaling_factors to something like [0.8] or [0.7]
> cfg.scaling_factors = [0.75]
> # you know you're looking just for squares so you can limit wh_ratio_range to something like: (0.8, 1.2)
> cfg.wh_ratio_range = (0.8, 1.2)
> cfg.dilation_iterations = 0
> ```
> 
> Do let me know how it went! Good luck!

Hi @karolzak 

Sorry it took me so long to respond. I had very limited time and tried your suggestion but didn't succeed. The program detected less checkboxes when i changed the scaling factor to something else than 0.5. I checked the size of the checkboxes and it was fine. So I had to write a test first, that checked through all sensible possibilities. My initial values seemed to be pretty close. scaling_factor = 0.5 and the selected width & height_range gave me the most detections for the testfile (but many other combinations did equivalent as well). Is there anything else to consider that it might work better? Thanks a lot!

**Comment by karolzak** [comment]
@FUF1 could you send me an example of one of your images? I'll try to run it with my code and see if I can crack it

**Comment by FUF1** [comment]
@karolzak  Thank you for the generous offer! Is there a way to send it to you non publicly since the tests should not be distributed unnecessarily? I tried to erase the content, but then the program seems to detect different things.

**Comment by karolzak** [comment]
@FUF1 can you send it via email? Send it over to: karol.zak at hotmail.com

**Comment by FUF1** [comment]
> karol.zak at hotmail.com

Yes, I sent it. 👍

**Comment by FUF1** [comment]
Tweaking the values with the suggestions of Karol resulted in a much higher success rate. Thanks again.
