### ISSUE TITLE
Unhandled exception when no rectangles found

### ISSUE THREAD

**Issue by shanepeckham** [karolzak/boxdetect#5]
Need to add to check and add graceful exception if no rects are found:
**--> 109     mean_width = np.mean(rects[:, 2])**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-9f7ae45d8ac4> in <module>
      2 
      3 rects, grouping_rects, img, output_image = get_boxes(
----> 4     os.path.join(DATA_PATH, file_name), config=config, plot=False)

/media/shane/HD/anaconda3/envs/nlp/lib/python3.7/site-packages/boxdetect/pipelines.py in get_boxes(img, config, plot)
    107     # merge rectangles into group if overlapping
    108     rects = group_countours(cnts_list)
--> 109     mean_width = np.mean(rects[:, 2])
    110     # mean_height = np.mean(rects[:, 3])
    111     # group rectangles vertically (line by line)

TypeError: tuple indices must be integers or slices, not tuple

**Comment by karolzak** [comment]
Thanks for picking that up. I did see that error during development but totally forgot about it.. Will fix in the next release!
